# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

julia:
  - 1.1
  - 1.3

os:
  - linux
  - osx
  # windows

matrix:
  fast_finish: true

notifications:
  email: false

addons:
  apt:
    packages:
    - xorg-dev

services:
  - xvfb

after_success:
  - if [[ "$TRAVIS_OS_NAME" == linux && "$TRAVIS_JULIA_VERSION" == "1.1" ]] ; then julia --project=. -e 'using Pkg;
                                                                                                         Pkg.add("Coverage");
                                                                                                         using Coverage;
                                                                                                         Codecov.submit(process_folder())' ; fi
